config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'event#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :home
  resources :user
  # Redundant
  resources :event
  resources :event do
    resources :attendance
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
# frozen_string_literal: true

class Attendance < ApplicationRecord
  #for Heroku
  #after_create :warning_host

  belongs_to :guest, class_name: 'User'
  belongs_to :event

  validates :stripe_customer_id,
            presence: true,
            uniqueness: true

  def warning_host
    AttendanceMailer.warning_email(self).deliver_now
  end

end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :host, class_name: 'User'
  has_many :attendances
  has_many :guests, class_name: 'User', through: :attendances

  validates :start_date,
            presence: true
  validate :is_passed?

  validates :duration,
            presence: true
  validate :duration_specs

  validates :title,
            presence: true,
            length: { in: 5..140 }

  validates :description,
            presence: true,
            length: { in: 20..1000 }

  validates :price, presence: true
  validates_inclusion_of :price, in: 1..1000

  validates :location,
            presence: true

  def end_date
    start_date + duration * 60
  end

  private

  def is_passed?
    start_date = self.start_date
    errors.add(:start_date, 'must be before end time') unless start_date > DateTime.now
  end

  def duration_specs
    errors.add(:duration, 'please select a valid duration') unless duration.positive? && (duration % 5).zero?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #for Heroku
  #after_create :welcome_send

  has_many :attendances
  has_many :events, through: :attendances
  has_many :events

  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  add_flash_types :danger, :info, :warning, :success
  
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
  
  before_action :authenticate_user!, only: [:new]
  before_action :is_host?, only: [:new]
  before_action :is_already_a_guest?, only: [:new]
  before_action :is_admin?, only: [:index]

  def index
    @attendances = Attendance.where(event_id: params[:event_id])
    @event = Event.find(params[:event_id])
  end

  def new
    @user = current_user
    @event = Event.find(params[:event_id])
    @attendance = Attendance.new
  end

  def create
    @user = current_user
    @event = Event.find(params[:event_id])
    @amount = (@event.price * 100)

      customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
      })

      charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: "Achat d'un produit",
      currency: 'eur',
      })
      
      @attendance = Attendance.create(guest: @user, event: @event, stripe_customer_id: customer.id)

    rescue Stripe::CardError => e
      flash[:error] = e.message
      render 'new'
  end

  private

#ne marchera que si la personne n'est pas admin (if)
  def is_host?
    @event = Event.find(params[:event_id])
    if current_user == @event.host
      flash[:danger] = "Tu ne peux participer, tu organises !"
      redirect_to event_path(params[:event_id])
    end
  end

  #ne marchera que si la personne ne participe pas (if)
  def is_already_a_guest?
    @event = Event.find(params[:event_id])
    if @event.guests.include? current_user
      flash[:danger] = "Tu participes déjà (idiot)"
      redirect_to event_path(params[:event_id])
    end
  end

  #ne marchera que si la personne est l'host (unless)
  def is_admin?
    @event = Event.find(params[:event_id])
    unless current_user == @event.host
      flash[:danger] = "Tu n'as pas l'autorisation"
      redirect_to event_path(params[:event_id])
    end
  end

end

app/controllers/event_controller.rb
# frozen_string_literal: true

class EventController < ApplicationController
  def index
  end

  def show
    @event = Event.find(params[:id])
    @guests = @event.guests
    @start_date = @event.start_date.strftime('%d/%m/%Y à %Hh%M')
    @end_date = @event.end_date.strftime('%d/%m/%Y à %Hh%M')
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(start_date: params[:event_start_date], duration: params[:event_duration],
                       title: params[:event_title], host: current_user, description: params[:event_description], price: params[:event_price], location: params[:event_location])
    if @event.save
      redirect_to event_path(@event.id), success: 'Ton événement est en ligne !'

    else
      flash.now[:danger] = 'Retente ta chance !'
      render :new
    end
  end

  def edit 
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(start_date: params[:event_start_date], duration: params[:event_duration],
      title: params[:event_title], host: current_user, description: params[:event_description], price: params[:event_price], location: params[:event_location])
      redirect_to event_path(@event.id), success: 'Edition validé !'
    else
      flash[:danger] = 'Retente ta chance !'
      render :edit, status: :unprocessable_entity
      flash.discard
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end

  def update; end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @events = Event.where(host: current_user)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(first_name: params[:user_first_name], last_name: params[:user_last_name],
                    description: params[:user_description])
      redirect_to user_path(@current_user.id), success: 'Profil édité !'
    else
      flash[:danger] = "Le profil n'a pas pu être édité !"
      render :edit, status: :unprocessable_entity
      flash.discard
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

  # private
# add by lolo - don't know the use
  # def same_user?
  #   @user = User.find(params[:id])
  #   current_user == @user ? nil : (redirect_to root_path)
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/attendance_helper.rb
# frozen_string_literal: true

module AttendanceHelper
end

app/helpers/event_helper.rb
# frozen_string_literal: true

module EventHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/attendance/create.html.erb
<h1>Votre paiement est confirmé !</h1>

<h2>Merci <%= @user.first_name %> pour votre achat</h2>

app/views/attendance/index.html.erb
<div class="row d-flex justify-content-around">
      <div class="col">

<div class="row justify-content-center">
  <%@attendances.each do |attendance|%>
    <div class="card border-info my-2 mx-3 border-radius rounded" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Participant numéro <%= @attendances.index(attendance) + 1 %> : </h5>
        <p class="card-text"><%= attendance.guest.first_name %> <%= attendance.guest.last_name %></p>
      </div>
    </div>
  <% end %>
</div>

<div class="row justify-content-center mt-2">
      <button class="btn btn-outline-warning btn-lg mx-3"><%= link_to 'Editer', edit_event_path(@event.id)%></button>
      <button class="btn btn-outline-warning btn-lg mx-3"> <%= link_to "Adios", event_path(@event.id), method: :delete, data: { confirm: "Sûr ? Votre sentence est irrévocable !" } %></button>
</div>
</div>
</div>

app/views/attendance/new.html.erb
<h1> Participer à l'événement <%= @event.title %> </h1>

<%= form_tag event_attendance_index_path do %>
      <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>

        <label class="amount">
          <span>Amount: <%= @amount %></span>
        </label>
      </article>
    <% end %>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Participation"
            data-amount="<%=@amount%>"
            data-locale="auto">
    </script>
<% end %>

app/views/event/edit.html.erb
<section class="mx-auto" style="width: 500px;">

<div class="row d-flex justify-content-around">

<!--Grid column-->
<div class="col-md-9 mb-md-0 mb-5">
<br>
<h2 class="h3-responsive font-weight-bold text-center my-4">Edite ton événement <%=@event.title%></h2>
            <%= form_tag url_for(action: 'update'), method: 'patch', class: 'contact-form', id: 'contact-form' do %>

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :event_start_date, "Date de l'événement" %>
                          <%= text_field_tag :event_start_date , nil, class: 'form-control', type:"date", value:@event.start_date%>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :event_duration, "Durée" %>
                          <%= text_field_tag :event_duration , nil, class: 'form-control', value: @event.duration%>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :event_title, "Ton super titre" %>
                          <%= text_field_tag :event_title , nil, class: 'form-control', value: @event.title %>
                        </div>
                    </div>
                </div>

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :event_description, "Description" %>
                          <%= text_field_tag :event_description , nil, class: 'form-control', value: @event.description%>
                        </div>
                    </div>
                </div>

                <!--Grid row-->
                  <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :event_price, "Prix de l'événement" %>
                          <%= text_field_tag :event_price , nil, class: 'form-control', value: @event.price%>
                        </div>
                    </div>
                </div>

                <!--Grid row-->
                  <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :event_location, "Où qu'il est?" %>
                          <%= text_field_tag :event_location, nil, class: 'form-control', value: @event.location%>
                        </div>
                    </div>
                </div>
                <br>
                <div class="text-center text-md-left">
                  <%= submit_tag "C'est parti !", class: 'btn btn-danger form-control' %>
                </div>

                <div class="status"></div>
                <br>
        <% end%>
</section>

app/views/event/index.html.erb
<div class="jumbotron p-6">
<h1 class="display-4 text-white ">Bonjour, bienvenue sur EventBright</h1>
<p class="lead text-white">Pour ceux qui adorent sortir.</p>
</div>
<div class="d-flex flex-wrap justify-content-center my-3">
  <% if user_signed_in? %>
    <button class="btn btn-outline-warning btn-lg"><%= link_to 'Créer un événement', new_event_path %></button>
  <% else %>
    <button class="btn btn-outline-warning btn-lg"><%= link_to 'Créer un compte', new_user_registration_path %></button>
    <button class="btn btn-outline-warning btn-lg"><%= link_to 'Se connecter', new_user_session_path %></button>
  <% end %>
</div>


<div class="d-flex flex-wrap justify-content-center">
<%Event.all.each do |event|%>
  <div class="card border-info my-2 mx-3 border-radius rounded" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Event numéro <%= Event.all.index(event) + 1 %></h5>
      <p class="card-text">"<%= event.title.capitalize %>"</p>
      <p class="card-text">Contributeur : <%= event.host.first_name %></p>
      <button class="btn btn-warning text-white btn-md"><%= link_to 'Retrouve-le', event_path(event.id)%></button>
    </div>
  </div>
<% end %>
</div>

app/views/event/new.html.erb
<section class="mx-auto" style="width: 500px;">

<div class="row d-flex justify-content-around">

<!--Grid column-->
<div class="col-md-9 mb-md-0 mb-5">
<br>
<h2 class="h3-responsive font-weight-bold text-center my-4">Propose ton incroyable événement</h2>
            <%= form_tag url_for(action: 'create'), method: 'post', class: 'contact-form', id: 'contact-form' do %>

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :event_start_date, "Date de l'événement" %>
                          <%= text_field_tag :event_start_date , nil, class: 'form-control', type:"date", value:Date.today%>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :event_duration, "Durée" %>
                          <%= text_field_tag :event_duration , nil, class: 'form-control', placeholder:"Uniquement valable en minutes"%>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :event_title, "Ton super titre" %>
                          <%= text_field_tag :event_title , nil, class: 'form-control', placeholder:"Alléchant - maximum 140 caractères"%>
                        </div>
                    </div>
                </div>

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :event_description, "Description" %>
                          <%= text_field_tag :event_description , nil, class: 'form-control', placeholder:"Alléchante - maximum 1000 caractères"%>
                        </div>
                    </div>
                </div>

                <!--Grid row-->
                  <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :event_price, "Prix de l'événement" %>
                          <%= text_field_tag :event_price , nil, class: 'form-control', placeholder:"Pas gratos, touche pas au grisbi!"%>
                        </div>
                    </div>
                </div>

                <!--Grid row-->
                  <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :event_location, "Où qu'il est?" %>
                          <%= text_field_tag :event_location, nil, class: 'form-control', placeholder:"Adresse complète, in Paris olalala"%>
                        </div>
                    </div>
                </div>
                <br>
                <div class="text-center text-md-left">
                  <%= submit_tag "C'est parti !", class: 'btn btn-danger form-control' %>
                </div>

                <div class="status"></div>
                <br>
        <% end%>
</section>

app/views/event/show.html.erb
<section class="h-100 gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card">
          <div class="rounded-top text-white d-flex flex-row" style="background-color: #000; height:200px;">
            <div class="my-3 mx-3">
              <h3><%= @event.title%></h3>
              <p>Du <%= @start_date %> au <%= @end_date %></p>
              <button type="button" class="btn btn-outline-light" data-mdb-ripple-color="dark" style="z-index: 1;"><%= link_to "Participer", new_event_attendance_path(@event.id) %>
              </button>
              <button type="button" class="btn btn-outline-light" data-mdb-ripple-color="dark" style="z-index: 1;"><%= link_to "Mon événement", event_attendance_index_path(@event.id) %>
              </button>
            </div>
          </div>
          <div class="p-4 text-black" style="background-color: #f8f9fa;">
            <div class="d-flex justify-content-end text-center py-1">
              <div>
                <p class="mb-1 h5"><%= @event.location%></p>
                <p class="small text-muted mb-0 mr-2">A Paris</p>
              </div>
              <div>
                <p class="mb-1 h5"><%= @event.duration%></p>
                <p class="small text-muted mb-0">Minutes</p>
              </div>
              <div class="px-3">
                <p class="mb-1 h5"><%= @guests.count%></p>
                <p class="small text-muted mb-0">Participants</p>
              </div>
              <div>
                <p class="mb-1 h5"><%= @event.price%></p>
                <p class="small text-muted mb-0">Euros</p>
              </div>
            </div>
          </div>
          <div class="card-body p-4 text-black">
              <p class="lead fw-normal mb-1">En savoir plus</p>
              <div class="p-4" style="background-color: #f8f9fa;">
              <p class="font-italic mb-1"><%= @event.description%></p>
            </div>
          </div>
            <div class="card-body p-4 text-black">
              <p class="lead fw-normal mb-1">Proposé par</p>
              <div class="p-4" style="background-color: #f8f9fa>">
                <p class="font-italic mb-1"><%= @event.host.first_name%> <%= @event.host.last_name%></p>
            </div>
          </div>
        </div>
        </div>
      </div>
            </div>
            </div>

    </div>
  </section>

app/views/home/index.html.erb
<div class="jumbotron p-5">
<h1 class="display-4 text-white ">Bonjour, bienvenue sur EventBright</h1>
<p class="lead text-white">Pour ceux qui adorent sortir.</p>
<div class="d-flex flex-wrap justify-content-center my-3">
    <button class="btn btn-outline-warning btn-lg"><%= link_to 'Nos événements', event_index_path %></button>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventBright</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/journal/bootstrap.min.css" integrity="sha384-QDSPDoVOoSWz2ypaRUidLmLYl4RyoBWI44iA5agn6jHegBxZkNqgm2eHb6yZ5bYs" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag  'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark sticky-top" >
    <%= link_to "EventBright", home_index_path , class: "nav-link navbar-brand" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto ">
  <li class="nav-item active">
     <%= link_to "Accueil", event_index_path , class: "nav-link" %>
  </li>
  <li class="nav-item">
  <% if user_signed_in? %>
   <%= link_to "Créer un événement", new_event_path , class: "nav-link"  %>
   <% else %>
   <%= link_to "Créer un événement", user_session_path , class: "nav-link"  %>
   <% end %>
  </li>
</ul>


<form class="form-inline my-3 my-lg-0 ">

<% if user_signed_in? %>

<div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
  <ul class="navbar-nav">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Mon profil
      </a>
      <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
      <li><a class="text-white my-2 my-sm-0"><%= link_to "Mon profil", user_path(current_user.id)%></a></li>
      <li><a class="text-white my-2 my-sm-0"><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, data: { confirm: "Prêt à vous déconnecter ?" } %></a></li>
      </ul>
    </li>
  </ul>
</div>

<% else %>

<div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
  <ul class="navbar-nav">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        S'inscrire / Se connecter
      </a>
      <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
      <li><a class="my-2 my-sm-0"><%= link_to "Se connecter", new_user_session_path %></a></li>
      <li><a class="my-2 my-sm-0"><%= link_to 'Créer un compte', new_user_registration_path %></a></li>
      </ul>
    </li>
  </ul>
</div>
<% end %>
  </div>
</form>

</div>
</nav>

<div class="align-self-center ">
<% flash.each do |name, msg| %>
  <div class='alert alert-<%= name %> text-center'>
  <%= msg %>
<% end %>
</div>

    <%= yield %>
  </body>
</html>

app/views/user/edit.html.erb
<section class="mx-auto" style="width: 500px;">

<div class="row d-flex justify-content-around">

<!--Grid column-->
<div class="col-md-9 mb-md-0 mb-5">
<br>
<h2 class="h3-responsive font-weight-bold text-center my-4">Edite ton profil</h2>
            <%= form_tag url_for(action: 'update'), method: 'patch', class: 'contact-form', id: 'contact-form' do %>

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :user_first_name, "Prénom" %>
                          <%= text_field_tag :user_first_name , nil, class: 'form-control', value: @user.first_name%>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :user_last_name, "Nom" %>
                          <%= text_field_tag :user_last_name , nil, class: 'form-control', value: @user.last_name%>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 form-group">
                          <%= label_tag :user_description, "Description" %>
                          <%= text_field_tag :user_description , nil, class: 'form-control', value: @user.description%>
                        </div>
                    </div>
                </div>

                <br>
                <div class="text-center text-md-left">
                  <%= submit_tag "C'est parti !", class: 'btn btn-danger form-control' %>
                </div>

                <div class="status"></div>
                <br>
        <% end%>
</section>

app/views/user/show.html.erb
<div class="container py-5 h-100">

  <div class="row d-flex justify-content-center align-items-center">
    <div class="card" style="width: 18rem;">
      <div class="card-body text-center">
        <h3 class="card-title">Ton profil</h3>
        <p class="card-text"><%= @user.description %></p>
      </div>
      <ul class="list-group list-group-flush text-center">
        <li class="list-group-item"><%= @user.first_name %></li>
        <li class="list-group-item"><%= @user.last_name %></li></li>
        <li class="list-group-item"><%= @user.email %></li>
      </ul>
      <div class="card-body text-center">
        <h5 class="card-title text-center mt-2">Édition</h5>
        <button class="btn btn-warning text-white btn-md card-link"><%= link_to "mail/mot de passe", edit_user_registration_path %></button>
        <button class="btn btn-warning text-white btn-md card-link mt-2"><%= link_to "reste du profil", edit_user_path(current_user.id) %></button>
      </div>
    </div>
  </div>

  <h2 class="text-center">Tes événements</h2>
  <div class="row d-flex justify-content-center align-items-center mt-4">

    <div class="d-flex flex-wrap justify-content-center">
      <% @events.each do |event| %>
        <div class="card border-info my-2 mx-3 border-radius rounded" style="width: 18rem;">
          <div class="card-body text-center">
            <h5 class="card-title">titre : <%= event.title %></h5>
            <button class="btn btn-warning text-white btn-md"><%= link_to 'Retrouve-le', event_path(event.id)%></button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>